format = "âœ–ï¸ $all"

[character]
success_symbol = "[ğŸ£ â¯â¯â¯](bold blue)"
error_symbol =  "[ğŸ£ â¯â¯â¯](bold red)"

[memory_usage]
disabled = false
threshold = -1
symbol = "ğŸ‘"
format = "$symbol [$ram](bold dimmed green) "
